name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpUnitTests:
    name: PHP ${{ matrix.phpVersion }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        phpVersion: ['8.1', '8.2', '8.3', '8.4']
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}-${{ matrix.phpVersion }}
      cancel-in-progress: true
    steps:
      - name: Setup Winter
        uses: wintercms/setup-winter-action@v1
        with:
          php-version: ${{ matrix.phpVersion }}
          plugin-author: winter
          plugin-name: search

      - name: Run tests
        run: php artisan winter:test -p Winter.Search
